# Generated by Django 4.1.4 on 2022-12-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=64)),
                ('building_number', models.CharField(max_length=8)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('picture', models.URLField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('cities', models.ManyToManyField(to='coffeeapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linkString', models.URLField()),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.coffeeshop')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.site')),
            ],
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='links',
            field=models.ManyToManyField(through='coffeeapp.Link', to='coffeeapp.site'),
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='tags',
            field=models.ManyToManyField(to='coffeeapp.tag'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='metro_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.metrostation'),
        ),
    ]
