# Generated by Django 4.1.4 on 2022-12-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrostation',
            name='cities',
        ),
        migrations.AddField(
            model_name='metrostation',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffeeapp.city'),
            preserve_default=False,
        ),
    ]
