# Generated by Django 4.1.4 on 2022-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_remove_metrostation_cities_metrostation_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeshop',
            name='links',
        ),
        migrations.AddField(
            model_name='coffeeshop',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
