# Generated by Django 4.1.4 on 2022-12-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0003_remove_coffeeshop_links_coffeeshop_link_delete_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='comment',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
