# Generated by Django 4.1.4 on 2022-12-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0004_coffeeshop_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='description',
        ),
    ]
